### PR TITLE
doc graphs and doc inspection

### PR DESCRIPTION
**Pull request by jonneguyt**
I've created a new tab that allows for graphs per doc. These graphs are clickable and produce a table with the document information.

I've also made minor improvements over the previous PRs

I think you can just check this one rather than any of the other ones

### CODE REVIEW

**Comment by cschwem2er** [comment]
Thank you! I should be able to check everything this week.

**Comment by cschwem2er** [comment]
All right so I will now start reviewing the PR. Am I correct in that I can ignore any other PR's and focus on your current development status in branch "doc_graphs"?

**Comment by jonneguyt** [comment]
Yes!

**Comment by cschwem2er** [comment]
Wow, you implemented several very nice features, thank you! I would suggest a number of small changes:

- standardize column names such that everything is in lower case.
- you might wanna rename "original document id" with for instance "stm document id", the original was a bit confusing at least for me.
- do not include original document id, row id and theta by default, but rather leave the corresponding boxes unchecked. I think it is a good idea to not throw too much stuff at people when they first open the app.
- Move all the document features from "Proportions(documents)" and "Document Graphs" in one joint dashboard panel.
- As you already included specific search options for every column of the document inspection data frame, I think you can remove the search that appears above this data frame (on the right-hand side of "show entries").
- please feel free to add yourself as a collaborator in the `DESCRIPTION` file. Here is an example of how this looks like: https://github.com/strengejacke/sjPlot/blob/master/DESCRIPTION

**Comment by jonneguyt** [comment]
> Wow, you implemented several very nice features, thank you! I would suggest a number of small changes:

Thanks. I implemented the changes suggested. I have also changed the NEWS entry, but have **not** changed the readme. Could you go over it again and let me know if this works better?

**Comment by cschwem2er** [comment]
Thanks! Unfortunately I cannot install the new version, it seems like the `DESCRIPTION` file is not properly formatted:
```

* installing *source* package 'stminsights' ...
Error : Invalid DESCRIPTION file

Malformed Authors@R field:
```

**Comment by cschwem2er** [comment]
Might just be a missing comma for separating the persons in the corresponding vector?

**Comment by jonneguyt** [comment]
Changed it, can you try again?

**Comment by cschwem2er** [comment]
Looks good, thank you! :) I'll merge the PR, update readme + vignettes and prepare a CRAN submission in the next days.

**Pull request merged**
